import dayjs from 'dayjs';
const today = Math.floor(Math.random() * (400) + 100);
const graphdata = [
        {   
            day:1,
            // datestring: dayjs().subtract(5, 'day').format('MM.DD'),
            date: dayjs().subtract(5, 'day').hour(5).valueOf(),
            time: '5시', 
            status: '공복',
            sugar: Math.floor(Math.random() * (400) + 100),
        },
        {
            day:1,
            date: dayjs().subtract(5, 'day').hour(9).valueOf(),
            status: '아침 식후',
            time: '9시', 
            sugar: Math.floor(Math.random() * (400) + 100),
        },
        {
            day:1,
            date: dayjs().subtract(5, 'day').hour(14).valueOf(),
            status: '점심 식후',
            time: '14시', 
            sugar: Math.floor(Math.random() * (400) + 100),
        },
        {
            day:1,
            date: dayjs().subtract(5, 'day').hour(20).valueOf(),
            time: '20시', 
            sugar: Math.floor(Math.random() * (400) + 100),
        },
        {   
            day:2,
            date: dayjs().subtract(4, 'day').hour(5).valueOf(),
            time: '5시', 
            status: '공복',
            sugar: Math.floor(Math.random() * (400) + 100),
        },
        {
            day:2,
            date: dayjs().subtract(4, 'day').hour(9).valueOf(),
            status: '아침 식후',
            time: '9시', 
            sugar: Math.floor(Math.random() * (400) + 100),
        },
        {
            day:2,
            date: dayjs().subtract(4, 'day').hour(14).valueOf(),
            status: '점심 식후',
            time: '14시', 
            sugar: Math.floor(Math.random() * (400) + 100),
        },
        {
            day:2,
            date: dayjs().subtract(4, 'day').hour(20).valueOf(),
            time: '20시', 
            status: '저녁 식후',
            sugar: Math.floor(Math.random() * (400) + 100),
        },
        {   
            day:3,
            date: dayjs().subtract(3, 'day').hour(5).valueOf(),
            time: '5시', 
            status: '공복',
            sugar: Math.floor(Math.random() * (400) + 100),
        },
        {
            day:3,
            date: dayjs().subtract(3, 'day').hour(9).valueOf(),
            status: '아침 식후',
            time: '9시', 
            sugar: Math.floor(Math.random() * (400) + 100),
        },
        {
            day:3,
            date: dayjs().subtract(3, 'day').hour(14).valueOf(),
            status: '점심 식후',
            time: '14시', 
            sugar: Math.floor(Math.random() * (400) + 100),
        },
        {
            day:3,
            date: dayjs().subtract(3, 'day').hour(20).valueOf(),
            time: '20시', 
            status: '저녁 식후',
            sugar: Math.floor(Math.random() * (400) + 100),
        },
        {   
            day:4,
            date: dayjs().subtract(2, 'day').hour(5).valueOf(),
            time: '5시', 
            status: '공복',
            sugar: Math.floor(Math.random() * (400) + 100),
        },
        {
            day:4,
            date: dayjs().subtract(2, 'day').hour(9).valueOf(),
            status: '아침 식후',
            time: '9시', 
            sugar: Math.floor(Math.random() * (400) + 100),
        },
        {
            day:4,
            date: dayjs().subtract(2, 'day').hour(14).valueOf(),
            status: '점심 식후',
            time: '14시', 
            sugar: Math.floor(Math.random() * (400) + 100),
        },
        {
            day:4,
            date: dayjs().subtract(2, 'day').hour(20).valueOf(),
            status: '저녁 식후',
            time: '20시', 
            sugar: Math.floor(Math.random() * (400) + 100),
        },
        {   
            day:5,
            date: dayjs().subtract(1, 'day').hour(5).valueOf(),
            time: '5시', 
            status: '공복',
            sugar: Math.floor(Math.random() * (400) + 100),
        },
        {
            day:5,
            date: dayjs().subtract(1, 'day').hour(9).valueOf(),
            status: '아침 식후',
            time: '9시', 
            sugar: Math.floor(Math.random() * (400) + 100),
        },
        {
            day:5,
            date: dayjs().subtract(1, 'day').hour(14).valueOf(),
            status: '점심 식후',
            time: '14시', 
            sugar: Math.floor(Math.random() * (400) + 100),
        },
        {
            day:5,
            date: dayjs().subtract(1, 'day').hour(20).valueOf(),
            status: '저녁 식후',
            time: '20시', 
            sugar: Math.floor(Math.random() * (400) + 100),
        },

        {   
            day:6,
            date: dayjs().hour(5).valueOf(),
            time: '5시', 
            status: '공복',
            sugar: Math.floor(Math.random() * (400) + 100),
        },
        {
            day:6,
            date: dayjs().hour(9).valueOf(),
            status: '아침 식후',
            time: '9시', 
            sugar: Math.floor(Math.random() * (400) + 100),
        },
        {
            day:6,
            date: dayjs().hour(14).valueOf(),
            status: '점심 식후',
            time: '14시', 
            sugar: Math.floor(Math.random() * (400) + 100),
        },
        {
            day:6,
            date: dayjs().hour(20).valueOf(),
            status: '저녁 식후',
            time: '20시', 
            sugar: Math.floor(Math.random() * (400) + 100),
        },
        // {   
        //     day:7,
        //     date: dayjs().add(1, 'day').hour(5).valueOf(),
        //     time: '5시', 
        //     status: '공복',
        //     sugar: Math.floor(Math.random() * (400) + 100),
        // },
        {
            day:7,
            date: dayjs().add(1, 'day').hour(9).valueOf(),
            status: '아침 식후',
            time: '9시', 
            sugar: Math.floor(Math.random() * (400) + 100),
        },
        {
            day:7,
            date: dayjs().add(1, 'day').hour(14).valueOf(),
            status: '점심 식후',
            time: '14시', 
            sugar: Math.floor(Math.random() * (400) + 100),
        },
        {
            day:7,
            date: dayjs().add(1, 'day').hour(20).valueOf(),
            status: '저녁 식후',
            time: '20시', 
            sugar: Math.floor(Math.random() * (400) + 100),
        },
        // {   
        //     day:8,
        //     date: dayjs().add(2, 'day').hour(5).valueOf(),
        //     time: '5시', 
        //     status: '공복',
        //     sugar: Math.floor(Math.random() * (400) + 100),
        // },
        {
            day:8,
            date: dayjs().add(2, 'day').hour(9).valueOf(),
            status: '아침 식후',
            time: '9시', 
            sugar: Math.floor(Math.random() * (400) + 100),
        },
        {
            day:8,
            date: dayjs().add(2, 'day').hour(14).valueOf(),
            status: '점심 식후',
            time: '14시', 
            sugar: Math.floor(Math.random() * (400) + 100),
        },
        {
            day:8,
            date: dayjs().add(2, 'day').hour(20).valueOf(),
            status: '저녁 식후',
            time: '20시', 
            sugar: Math.floor(Math.random() * (400) + 100),
        }
]
export default graphdata;